### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by pdavidow** [turion/rhine#122]
Is there a text-based basic tutorial for Rhine?

**Comment by turion** [comment]
I added a documentation section to the readme here: https://github.com/turion/rhine/blob/develop/README.md#documentation
This is currently everything there is. If you can get your hands on the article that's your best starting point. I currently don't have a PDF handy, unfortunately, otherwise I'd upload and link that. Possiby @ivanperez-keera has a PDF somewhere?

**Comment by turion** [comment]
@ivanperez-keera do you know some documentation that I've missed, e.g. a recording of your ICFP talk?

**Comment by turion** [comment]
On Ivan's site I found a link to the PDF. It's now linked in https://github.com/turion/rhine/blob/develop/README.md#documentation. This is the best starting point as it explains the library and the concepts behind it in a simple example application.

If you find a problem with the tutorial in the article, don't hesitate to open an issue here.

**Comment by pdavidow** [comment]
The article is $15
https://dl.acm.org/purchase.cfm?id=3242757

**Comment by turion** [comment]
@pdavidow I've updated the link further, now it should really work.

**Comment by pdavidow** [comment]
Thanks -- now the article is free!

**Comment by ivanperez-keera** [comment]
I have to request that they release the talk. I was waiting for the video to check something before the release.

I got the video a few weeks ago, but have been too busy with papers.
