### ISSUE TITLE
GlossEventClockIO

### ISSUE THREAD

**Issue by reubenharry** [turion/rhine#189]
I notice that time doesn't progress with this clock, in the sense that `sinceLastS` seems to always output 0. Is this intended, and if so, is there a way I can still get the time?

(For context, I want to write a rhine-bayes example with the green dot's position being given by the user's cursor)

**Comment by turion** [comment]
Ah, this is a nasty bug. Can you add a `GlossSimClockIO` to your `Rhine` somewhere? That should work around it for a moment.

**Comment by turion** [comment]
Ah, that doesn't solve the bug either it seems. PR upcoming.

**Comment by turion** [comment]
Can you have a look whether `rhine-gloss` at https://github.com/turion/rhine/pull/190 fixes your example?

**Comment by reubenharry** [comment]
Thanks! This is a bit of a basic question, but what's the best way of using #190? That is, if I clone and build that PR, how do I then import that version of Rhine in my rhine-bayes-examples repo?

**Comment by turion** [comment]
Depends on whether you use stack or cabal. (I recommend cabal because it seems that stack doesn't see much maintenance anymore.) I think you use stack. There you can specify a git repository and commit to pin a dependency to a specific version: https://docs.haskellstack.org/en/stable/pantry/#git-and-mercurial-repositories. That part can be removed once I've released a new version.

**Comment by turion** [comment]
I'm assuming that this is fixed on latest master. Does that work for you? If not feel free to reopen.

**Comment by reubenharry** [comment]
Yes, fixed!
