### ISSUE TITLE
not accepting `rhine` 1.4.0.1?

### ISSUE THREAD

**Issue by alaendle** [turion/rhine#336]
https://github.com/turion/rhine/blob/7c866688458fcf8993c29a317ce892899b7268f9/rhine-gloss/rhine-gloss.cabal#L45

Just spotted this while reading through the stackage constraints file...

**Comment by turion** [comment]
You're right, I just fixed it here: https://github.com/turion/rhine/pull/331/

**Comment by turion** [comment]
Regarding the [stackage commit](https://github.com/commercialhaskell/stackage/commit/18b1cf854865e84df16e6ce0a6b28452fd232a0d): Thank you very much :) I didn't quite manage to keep it up to date due to being busy with other projects, and I appreciate your work there! I believe that all `rhine*` packages and `automaton` should be able to build on stackage nightly, I just didn't come around to testing that.
