### ISSUE TITLE
Trying to design a function

### ISSUE THREAD

**Issue by reubenharry** [turion/rhine#364]
Is there a sensible way to implement a function of this type:

```haskell
commute :: MonadDistribution m => ClSF m t a b -> ClSF Identity t a (m b)
```

(The reason this occurred to me is that I often view the type `MonadDistribution m => ClSF m t () a`  as a (discretized)  representation of a stochastic differential equation (or rather, the dynamics that an SDE implies), and `MonadDistribution m => ClSF Identity t () (m a)` as a representation of the flow given by the corresponding Fokker-Planck equation.)

If this existed, I'd also wonder if I could use it to write a particle filter, adding resampling by acting on the `m b` at arbitrary times.

I had a go (using the old MSF implementation):

```haskell
commute :: (Monad m, Applicative n) => MSF m a b -> MSF n a (m b)
commute (MSF inp) = MSF \x -> let b = inp x in pure (fst <$> b, attempt $ performOnFirstSample $ snd <$> b)
```

but this seems to have a memory leak (which I think is to be expected), and I don't even know if it does what I think it does.

**Comment by turion** [comment]
Yes, coincidentally I've been working in that direction: https://github.com/turion/rhine/commit/cdcef02da39bf1857db8208a37b3f561b95aac9c
It can even be a bit generalised. The bare `Identity` is a bit weird, and we can do a bit better by taking a composition of functors, and pushing the inner functor to the output. Take `handleCompose` and specialise `m` to `Identity` to get your required function.

What you're saying about SDEs makes a lot of sense. But I think in general the result of your function is less usable. For example when you apply resampling on the output it will have no effect on the output of subsequent ticks. Pretty much because you've hidden away the control and only observe the output.

**Comment by turion** [comment]
So actually your function is more akin to https://hackage.haskell.org/package/rhine-bayes-1.4.0.1/docs/FRP-Rhine-Bayes.html#v:runPopulationCl. After we apply `runPopulationCl`, we lose the ability to resample as well.

**Comment by reubenharry** [comment]
Relatedly, I think there must be a connection between the Feynman-Kac notion of a particle filter, and what we are doing (see https://archive.org/details/springer_10.1007-978-1-4684-9393-1/page/n7/mode/2up?view=theater).
